module agr
  !! Very basic utilities to generrates grace project files.
  implicit none
contains
subroutine agr_init(uf)
  !! Initialize an agr file.
  implicit none
  integer,intent(in) :: uf !! file descriptor of the file.

  character(len=5) :: zonea
  character(len=8) :: datea
  character(len=10) :: timea
  
  write(uf,'(A)') "# Grace file type"
  write(uf,'(7A)') "# Generated by ismc2  ", datea,", ",timea," ",zonea, " UTC."
end subroutine agr_init

subroutine agr_add_xy(uf,set,x,y,n)
  !! Adds a XY set to an agr file.
  implicit none
  integer,intent(in) :: uf !! file descriptor
  integer, intent(in) :: n !! size of the set
  integer, intent(in) :: set !! number of the set
  real(8) :: x(n)            !! X values
  real(8) :: y(n)            !! Y values

  integer :: i

  write(uf,'(a,i0)') "@target g0.s",set
  write(uf,'(a)') "@type xy"

  do i=1,n
     write(uf,'(2g17.8)') x(i),y(i)
  end do

  write(uf,'(a1)') "&"

end subroutine agr_add_xy

end module agr
